### ISSUE TITLE
MQTT 

### ISSUE THREAD

**Issue by jsponz** [Lightwell-bg/LWClock#1]
Thanks for your nice project. I really like it. 

My only question is about MQTT. I have made the configuration for the connection to my broker and I receive different values as the ones shown on the admin panel.

<img width="864" alt="Bildschirmfoto 2020-02-12 um 11 22 03" src="https://user-images.githubusercontent.com/12778286/74327554-b1162480-4d8c-11ea-9a6b-a81240c8687c.png">

<img width="335" alt="Bildschirmfoto 2020-02-12 um 11 22 16" src="https://user-images.githubusercontent.com/12778286/74327582-bbd0b980-4d8c-11ea-8b89-4663448e9bfb.png">

Any help?

Thanks in advance.

P.S: I am using your default compilation v2.0

**Comment by Lightwell-bg** [comment]
You need to configure the settings for MQTT on page
![image](https://user-images.githubusercontent.com/56789928/74357429-93ff4700-4dc8-11ea-8fc9-99b50b3d2a87.png)
You can find this page in menu when you are on "Setup".

**Comment by jsponz** [comment]
It is already configured. I receive date in the MQTT broker, but the values
are different. Check the screens.

Thanks!

**Comment by Lightwell-bg** [comment]
I understood. In scetch is correction for temp and hum depending on the brightness of the indicator. But no correction for sending to MQTT and thingspeak.com.  This was done when the sensor was inside the case.
switch (brightnow) {
    case 0:
      tempBME = tempBME - 0.09;
    break;
    case 1:
      tempBME = tempBME - 0.57;
    break;
    case 2:
      tempBME = tempBME - 1.04;
    break;
    case 3:
      tempBME = tempBME - 1.66;
.....................
I can remote correction or enable/disable it in the web interface

**Comment by jsponz** [comment]
Ok. I guess that explains also the difference for the other values.

Maybe a good idea is to have the change to make the corrections from the
admin panel. For example for the temperature from -5 to +5 and the user
based on the case decides to make the correction.

**Comment by Lightwell-bg** [comment]
I'll make on/off correction and choice of "mm" or hPa (for pressure) with admin panel

**Comment by jsponz** [comment]
Ok. Thanks!

Looking forward to it!

**Comment by Lightwell-bg** [comment]
I've added a selection of disabling adjustments for temp&hum and select unit for pressure (only for send to MQTT). Please update FS and scetch.

**Comment by jsponz** [comment]
Thanks! I will check it!

**Comment by jsponz** [comment]
Just to confirm it works! Thanks!
