### ISSUE TITLE
Wrong version information on the compiled version

### ISSUE THREAD

**Issue by jsponz** [Lightwell-bg/LWClock#2]
I have just used the version "LWClockV2.0-noRTC.bin", but the version information is wrong. Check attached image. 

<img width="372" alt="Bildschirmfoto 2020-02-18 um 08 27 42" src="https://user-images.githubusercontent.com/12778286/74714576-16ee2a80-522b-11ea-9a77-cb26bff3868b.png">

**Comment by Lightwell-bg** [comment]
Please update firmware with new BIN file
