### ISSUE TITLE
FileNotFound

### ISSUE THREAD

**Issue by AlexKholodkov** [Lightwell-bg/LWClock#3]
Hi, thanks for your wonderful project!
But at the first start, I can’t see the web interface, in the browser I see only FileNoteFound  ( successfully connected to AP 192.168.4.1)

> 
11:20:57.137 -> Failed to open config file
11:20:57.270 -> FileConfig
11:20:57.270 -> Start screen
11:20:57.270 -> Loading config EEPROM
11:20:57.469 -> ........Start WIFI

**Comment by Lightwell-bg** [comment]
You must upload SPIFFS. File spiffs.bin
14. Upload the sketch data files (the data directory in the sketch folder) using Tools > ESP8266 Sketch Data Upload.

**Comment by AlexKholodkov** [comment]
Ok, thanks a lot!
(https://github.com/esp8266/arduino-esp8266fs-plugin)
