### ISSUE TITLE
No file found at webpage 192.168.4.1

### ISSUE THREAD

**Issue by ChrLHL** [Lightwell-bg/LWClock#5]
Hi Lightwell,

I just assembelt your clock. The electric works so far, but i cant reach the webpage to configurate the clock.

The only output I get is FileNotFound .

Could you have  a look on it?

Thak you very much.
Best regards
Christian

**Comment by Mohin2005** [comment]
Hey @ChrLHL , I am interested in your project, could your please share your project to me? So that I can try to help you out of this

**Comment by ChrLHL** [comment]
Hi Mohin2005,

thanks that would be great.
So first of all, i used the 3D prnted case, i will cut out the plexiglas soon.
I dind't used the pcb, instead i printed a holder for all of the single components an wired them. 

So the wireing is correcht an the clock shows date time and after a while the data from the BMP. The BMP reads heat emmisions from the other components, here also be said, thats the first "prototype" oft the wired solution.

When i start the LW clock everything is working.
Then id like to configurate the time, date and so on over the web interface. As in the instruction I connect my phone to the wifi of the esp and browse to 192.168.4.1.

Now the problem is that i reach the webpage but there is no content on it. 
i see that:

![grafik](https://user-images.githubusercontent.com/59566342/95221886-348ef500-07f8-11eb-832d-921a1e332082.png)


So thats all.Oh thats not all, sorry.
As i programmed the esp there is to mention that i am not sure about the step 8. "In Tools > Flash Size: select 4M (1M SPIFFS) -- this project requires SPIFFS for saving and reading configuration settings."
Well i Choose those Settings:

![grafik](https://user-images.githubusercontent.com/59566342/95224775-605faa00-07fb-11eb-9d2e-769f1d334954.png)

Sould there be the option SPIFFS instead of OTA? 
The flash sizes are correct, ist just a screenshot from the menu.

Now thats all.


Thank you very much so far.
Best regards
Christian

**Comment by Lightwell-bg** [comment]
....
14. Upload the sketch data files (the data directory in the sketch folder) using Tools > ESP8266 Sketch Data Upload.

**Comment by ChrLHL** [comment]
Hi,

thanks for the help. Of course the error was sitting in front of the screen ;-).

But i've got another, possible not so dump, question.  I'd like to tun of the diagonal fading of the time and just want, that the screen clears itself witout any effect. So if just time is displayed it looks more or less static. 

Thanks a lot 
Christian

**Comment by Freeejack** [comment]
Hi,

I have the same issue like above. FileNotFound. Checked many times every library and uploaded the sketch (lwclockv22.ino) and data, but no success. 

What can cause this?

It works like all the leds are on, but nothing more. Can you please help me with this?

**Comment by Lightwell-bg** [comment]
Hi,
Do you use version with SPIFFS or LITTLFFS?
![image](https://user-images.githubusercontent.com/56789928/102354380-89e73f80-3fbb-11eb-807a-e9f637ec2a28.png)

**Comment by Freeejack** [comment]
Hi, 
Thank you for the fast answer. In have only the Sketch Data Upload menu item. The littleFS no, so this is the source of the error? 

Edit: i tried with LittleFS, it works now! I can access the settings page and the temp sensor is works too. 

My only one, but big problem now is that the led panel always switch on every led and shows nothing else. I double checked the wires, I don't know what's the error. It's a bad panel or it's possible that it's software related?

**Comment by Lightwell-bg** [comment]
I think you have bad connection or bad panels.

**Comment by Lightwell-bg** [comment]
Arduino ESP8266 LittleFS Filesystem Uploader
https://github.com/earlephilhower/arduino-esp8266littlefs-plugin
