### ISSUE TITLE
wont connect to wifi

### ISSUE THREAD

**Issue by victor7376** [Lightwell-bg/LWClock#6]
I've followed all guide and then put in my wifi details but nothing happens it just refuses to connect and keeps in AP mode.

I've tried resetting to factory defaults but it still has the wifi details within the page that should of been reset.

Any help would be grateful.

**Comment by Freeejack** [comment]
I have this problem too. I changed my wifi router to a newer model, and after that it wont connect to wifi. The weather is not displayed. The system remains in AP mode, i can connect to the clock with the 192.168.4.1 IP address.
If i switch off the new router and connect back the old one, it works like a charm. What can cause this problem? SSID and pass not changed.

**Comment by Lightwell-bg** [comment]
I think you have problem with router or ESP board (unfortunately on the market there are a lot of low-quality ESP8266). Try to change ESP board.

**Comment by Freeejack** [comment]
Thanks for the answer. Because with my old router it works as expected i don't think that the board are the source of this error. But everything in my house (20+ wifi devices) works without any error with the new router.
Thanks in advance, i try another code and it turns out what's wrong.
